### PR TITLE
Up'ng Auto-Matter version to work with Jackson 2.8+

### PR DESCRIPTION
**Pull request by zvozin**
Please?

### CODE REVIEW

**Comment by rculbertson** [comment]
Looks like the maven-enforcer-plugin is failing the build because auto-matter 0.13.3 pulls in a more recent version of guava. Would be happy to merge once that's fixed.

**Comment by zvozin** [comment]
How do you mean 'fixed'? ;)

**Comment by huysamen** [comment]
Hi guys.  Any way this can make it into Maven Central any time soon?  The official Google client is a bit useless (hangs indefinitely without errors on first call) but maintaining our own custom branch of this seems a bit tedious.

**Comment by rculbertson** [comment]
Closing in favor of #25, which also pulls in Guava 19.0 to avoid the issue with the enforcer plugin.

**Pull request closed without merging**
