### PR TITLE
Do not unwrap non CompletableException

### PR DESCRIPTION
**Pull request by jwiklund**
Avoid unwrapping non CompletableExceptions to avoid hanging on errors.

### CODE REVIEW

**Comment by jwiklund** [comment]
@danielnorberg

**Comment by danielnorberg** [comment]
Thanks for the PR! I think the issue might be in `toCompletableFuture()` however, so I submitted an alternative PR #36 to address that.

Does that solve your issue?

**Comment by danielnorberg** [comment]
Actually after looking/thinking some more I wonder if the CompletionException unwrapping is unnecessary.

Removed it in another commit to #36. Wdyt?

**Comment by danielnorberg** [comment]
This should be fixed by #36. Closing.

**Pull request closed without merging**
